
# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
trigger:
- dev
pool:
  vmImage: ubuntu-latest
strategy:
  matrix:
    SnowflakePython:
      python.version: '3.9'
 
variables:
  - group: 'sfkey-group' 
steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'
- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install dependencies'
- task: replacetokens@5
  inputs:
     targetFiles: 'secret_dev.json'
     encoding: 'auto'
     tokenPattern: 'default'
     writeBOM: true
     actionOnMissing: 'warn'
     keepToken: false
     actionOnNoFiles: 'continue'
     enableTransforms: false
     enableRecursion: false
     useLegacyPattern: false
     enableTelemetry: true
    
- script: pytest test_snowflake_connector.py 
  displayName: "pytest"